trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ARM_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
  ARM_TENANT_ID: $(AZURE_TENANT_ID)
  ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
  ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
  DATABRICKS_HOST: $(DATABRICKS_HOST)
  DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)

stages:
  - stage: Terraform_Deployment
    displayName: "Terraform Deployment"
    jobs:
      - job: Terraform
        displayName: "Terraform Apply"
        steps:
          - checkout: self

          - task: TerraformInstaller@0
            displayName: "Install Terraform"
            inputs:
              terraformVersion: '1.5.7'

          - script: terraform init
            displayName: "Terraform Init"
            workingDirectory: terraform

          - script: terraform plan -lock=false
            displayName: "Terraform Plan"
            workingDirectory: terraform

          - script: terraform apply -auto-approve
            displayName: "Terraform Apply"
            workingDirectory: terraform
            condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
